version: '3.7'

services:
    
    rabbitmq:
        image: 'rabbitmq:3.8.22-management-alpine'
        container_name: cookapp_rabbitmq
        hostname: 'cookapp_rabbitmq'
        restart: unless-stopped
        ports:
            - 5630:5672
            - 8090:15672
        env_file:
            - ./.env

    mysql:
        image: 'mariadb:10.6'
        container_name: 'cookapp_mysql'
        hostname: 'cookapp_mysql'
        restart: unless-stopped
        ports:                                                           
            - 3360:3306
        env_file:
            - ./.env

    mssql:
        image: 'mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04'
        container_name: 'cookapp_mssql'
        hostname: 'cookapp_mssql'
        restart: unless-stopped
        ports:                                                           
            - 1431:1433
        env_file:
            - ./.env

    mongodb:
        image: 'mongo:5.0.6-focal'
        container_name: 'cookapp_mongodb'
        hostname: 'cookapp_mongodb'
        restart: unless-stopped
        ports:                                                           
            - 27018:27017
        env_file:
            - ./.env
    
    backoffice_backend:
        image: 'cookapp_backoffice_backend:latest'
        container_name: 'cookapp_backoffice_backend'
        hostname: 'cookapp_backoffice_backend'
        build: ./backoffice
        restart: unless-stopped
        ports:
            - "5001:5000"
        volumes:
            - ./backoffice:/src/app
        env_file:
            - ./backoffice/.env
        depends_on:
            - rabbitmq
            - mysql
        command: gunicorn --reload --bind 0.0.0.0:5000 Main:app
    
    backoffice_backend_test:
        image: 'cookapp_backoffice_backend_test:latest'
        container_name: 'cookapp_backoffice_backend_test'
        hostname: 'cookapp_backoffice_backend_test'
        build: ./backoffice
        restart: 'no'
        volumes:
            - ./backoffice:/src/app
        command: python -m unittest discover -s /src/app/tests -p "*Test.py"
    
    
    