version: '3.7'

services:
    
    rabbitmq:
        image: 'rabbitmq:3.8.22-management-alpine'
        container_name: cookapp_rabbitmq
        hostname: 'cookapp_rabbitmq'
        restart: unless-stopped
        ports:
            - 5630:5672
            - 8090:15672
        env_file:
            - ./.env

    backoffice_mysql:
        image: 'mariadb:10.6'
        container_name: 'cookapp_backoffice_mysql'
        hostname: 'cookapp_backoffice_mysql'
        restart: unless-stopped
        ports:                                                           
            - 3360:3306
        env_file:
            - ./backoffice/.env
    
    backoffice_backend:
        image: 'cookapp_backoffice_backend:latest'
        container_name: 'cookapp_backoffice_backend'
        hostname: 'cookapp_backoffice_backend'
        build: ./backoffice
        restart: unless-stopped
        ports:
            - "5001:5000"
        volumes:
            - ./backoffice:/src/app
        env_file:
            - ./backoffice/.env
        depends_on:
            - rabbitmq
            - backoffice_mysql
        command: gunicorn --reload --bind 0.0.0.0:5000 Main:app
    
    backoffice_backend_test:
        image: 'cookapp_backoffice_backend_test:latest'
        container_name: 'cookapp_backoffice_backend_test'
        hostname: 'cookapp_backoffice_backend_test'
        build: ./backoffice
        restart: 'no'
        volumes:
            - ./backoffice:/src/app
        command: python -m unittest discover -s /src/app/tests -p "*Test.py"
    
    preparation_mssql:
        image: 'mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04'
        container_name: 'cookapp_preparation_mssql'
        hostname: 'cookapp_preparation_mssql'
        restart: unless-stopped
        ports:                                                           
            - 1431:1433
        env_file:
            - ./preparation/.env
    
    preparation_backend:
        image: 'cookapp_preparation_backend:latest'
        container_name: 'cookapp_preparation_backend'
        hostname: 'cookapp_preparation_backend'
        build: ./preparation
        restart: unless-stopped
        ports:
            - "5002:5000"
        volumes:
            - ./preparation:/src/app
            - /src/app/obj
        env_file:
            - ./preparation/.env
        depends_on:
            - rabbitmq
            - preparation_mssql
        command: /bin/bash ./entrypoint.sh
    
    preparation_backend_test:
        image: 'cookapp_preparation_backend_test:latest'
        container_name: 'cookapp_preparation_backend_test'
        hostname: 'cookapp_preparation_backend_test'
        build: ./preparation
        restart: 'no'
        volumes:
            - ./preparation:/src/app
            - /src/app/obj
        command: dotnet test
    
    
    